[mongodb]
mongodb.awsb26raman.xyz

[redis]
redis.awsb26raman.xyz

[mysql]
mysql.awsb26raman.xyz

[rabbitmq]
rabbitmq.awsb26raman.xyz

[catalogue]
catalogue.awsb26raman.xyz

[cart]
cart.awsb26raman.xyz

[user]
user.awsb26raman.xyz

[shipping]
shipping.awsb26raman.xyz

[payment]
payment.awsb26raman.xyz

[frontend]
frontend.awsb26raman.xyz

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar